first version
ArtemGomer/Network_nsu pull request #1
Opened 2020-09-13 14:22 UTC by ArtemGomer

Добавил первую версию первой лабы.

2020-09-15 16:05 UTC, Aloomenon requested changes
Ух, я уже сегодня это видел.
1) почитайте про .gitignore
2) зачем нужно закрывать сокеты, как и когда это нужно делать?

2020-09-16 12:40 UTC, ArtemGomer commented
> Ух, я уже сегодня это видел.
> 
> 1. почитайте про .gitignore
> 2. зачем нужно закрывать сокеты, как и когда это нужно делать?

Это просто вопрос на подумать или в коде есть какие-то ошибки?

2020-09-16 13:54 UTC, Aloomenon commented
Первый, на почитать, возможно применить.
Второй, на разобраться что это и к чему. Посмотреть как сейчас сделано, если все ок, то будем смотреть дальше, если нет то исправить и будем смотреть дальше.

2020-09-17 03:11 UTC, ArtemGomer commented
> Первый, на почитать, возможно применить.
> Второй, на разобраться что это и к чему. Посмотреть как сейчас сделано, если все ок, то будем смотреть дальше, если нет то исправить и будем смотреть дальше.

Ну, сокеты нужно закрывать, потому что в операционной системе есть ограничение на количество открытых сокетов. Мое приложение заканчивает работу только аварийно, т.к отправка сообщений идет в цикле while(true), и сокеты правильно не закрываются. Можно, конечно, запускать приложение в отдельном потоке и обрабатывать выход по interrupt. Если это нужно, могу сделать.

2020-09-20 13:41 UTC, Aloomenon commented
Сделайте возможность выхода из приложения.

2020-09-21 09:20 UTC, ArtemGomer commented
@Aloomenon , пингую, как вы и сказали))

2020-09-24 16:49 UTC, ArtemGomer commented
@Aloomenon

2020-09-24 16:53 UTC, Aloomenon requested changes

2020-09-24 16:53 UTC, Aloomenon commented on Lab1/src/Main.java
> +            System.exit(1);
к этому моменту сокеты уже открыты или нет?

2020-09-24 16:56 UTC, ArtemGomer commented on Lab1/src/Main.java
> +            System.exit(1);
Если они открывались, то значит выпал эксепшн в другом методе и сокеты закрылись(сделал в последнем комите). Либо они вообще не открывались.

2020-09-24 17:06 UTC, ArtemGomer commented on Lab1/src/Main.java
> +            System.exit(1);
Ну хотя, sender может построиться, а в receiver произойти ошибка. Тогда один сокет не будет закрыт

2020-09-24 18:26 UTC, ArtemGomer commented
@Aloomenon , сделал изменения. Должны быть последние. Все сокеты закрываются при любых ошибках.

2020-09-25 03:59 UTC, Aloomenon commented
ок не буду мучать вас. Принимаю.

2020-09-25 03:59 UTC, Aloomenon approved these changes

2020-09-25 04:40 UTC, ArtemGomer commented
Lab1

2020-09-25 04:41 UTC, merged