Lab3
ArtemGomer/Network_nsu pull request #3
Opened 2020-10-23 15:47 UTC by ArtemGomer

@Aloomenon , проверьте, пожалуйста)

2020-10-25 09:20 UTC, Aloomenon requested changes

2020-10-25 09:20 UTC, Aloomenon commented on Lab3/src/ClientMain.java
> +                        ChatClient chatClient = new ChatClient(name, port, lossPercentage);
а закрывать кто будет?

2020-10-25 09:20 UTC, Aloomenon commented on Lab3/src/ClientStuff/ChatClient.java
> +        receiver.interrupt();
что произойдет с тредом?

2020-10-25 09:20 UTC, Aloomenon commented on Lab3/src/ClientStuff/ChatClient.java
> +        receiver.interrupt();
я, конечно же, с точки зрения ресурсов, которые в нем.

2020-10-25 09:57 UTC, ArtemGomer commented on Lab3/src/ClientMain.java
> +                        ChatClient chatClient = new ChatClient(name, port, lossPercentage);
Вроде незакрытых сокетов не будет. Ели вылетит исключение, то сокет не создался -> клиент не создался. Потом сокет закрывается по команде.

2020-10-25 10:01 UTC, ArtemGomer commented on Lab3/src/ClientStuff/ChatClient.java
> +        receiver.interrupt();
При вызове interrupt внутри потока ставится флаг, который потом можно будет проверить isInterrupted или Thread.interrupted и выйти из метода run().

2020-10-25 10:10 UTC, ArtemGomer commented on Lab3/src/ClientStuff/ChatClient.java
> +        receiver.interrupt();
@Aloomenon

2020-10-29 04:09 UTC, ArtemGomer commented
@Aloomenon

2020-11-08 07:26 UTC, merged